import requests

"""
WARNING: DO NOT EDIT THIS FILE. IT IS USED TO CHECK YOUR SOLUTION AND MAY BE REPLACED BY THE TEACHER'S VERSION DURING GRADING.
"""

response = requests.get("https://edumail.fr/formations/sims/check.php", headers={
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/122.0.0.0 Safari/537.36"
    )
})
tradingData = response.json()

"""
WARNING: DO NOT EDIT THIS FILE. IT IS USED TO CHECK YOUR SOLUTION AND MAY BE REPLACED BY THE TEACHER'S VERSION DURING GRADING.
"""

try:
    response = requests.post("http://localhost:5000/orders", json=tradingData, timeout=2, headers={
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/122.0.0.0 Safari/537.36"
    )
})
    data = response.json()
except requests.exceptions.RequestException as e:
    print(f"Error occurred: {e}")
    data = {"error": str(e)}

"""
WARNING: DO NOT EDIT THIS FILE. IT IS USED TO CHECK YOUR SOLUTION AND MAY BE REPLACED BY THE TEACHER'S VERSION DURING GRADING.
"""

response = requests.post("https://edumail.fr/formations/sims/check.php", json=data, headers={
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/122.0.0.0 Safari/537.36"
    )
})
print(response.json())